[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "evalmyai"
description = "EVALMY.AI Python library"
version = "0.1.0"
dependencies = [
    "requests",
    "pandas",
]

[tool.setuptools.packages.find]
where = ["src"]
